# https://help.github.com/ja/github/automating-your-workflow-with-github-actions

name: Java CI

on: [push]

#services:

jobs:
  build:

    runs-on: ubuntu-latest

    # https://github.com/actions
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    # https://help.github.com/ja/github/managing-packages-with-github-package-registry/about-github-package-registry
    - name: Deploy
      env:
        GITHUB_TOKEN: ${{ secrets.TOKUO_SAND_SECRET }}
      run: |
        echo "<settings><servers><server><id>github</id><username>OWNER</username><password>${GITHUB_TOKEN}</password></server></servers></settings>" > ~/.m2/settings.xml
        mvn deploy
